build: false
platform:
 - x64
 - x86
clone_depth: 1
clone_folder: C:\projects\ps-install-php

environment:
  matrix:
    - dependencies: php70
      php_ver_target: 7.0
    - dependencies: php71
      php_ver_target: 7.1
    - dependencies: php72
      php_ver_target: 7.2

matrix:
  fast_finish: true

init:
  - SET PHP=1
  - SET PATH=C:\Program Files\OpenSSL;C:\tools\php;%PATH%
  - SET ANSICON=121x90 (121x90)
  - REG ADD "HKEY_CURRENT_USER\Software\Microsoft\Command Processor" /v DelayedExpansion /t REG_DWORD /d 1 /f

install:
  # Install PHP
  - IF EXIST C:\tools\ps-install-php (SET PHP=0)
  - ps: if (-not (Test-Path C:\tools\ps-install-php)) {.\Install-PHP.ps1 -Debug -InstallPath C:\tools\php -Version $Env:php_ver_target -Highest -Arch $env:platform -Extensions mbstring,intl,openssl,fileinfo,curl}
